// Sources/Models/TarotCard.swift
import Foundation

public enum ElementType: String, Codable, Sendable, CaseIterable {
    case fire = "FIRE"
    case water = "WATER"
    case earth = "EARTH"
    case air = "AIR"
    case spirit = "SPIRIT"
    
    public var platonicSolid: String {
        switch self {
        case .fire: return "TETRAHEDRON"
        case .earth: return "HEXAHEDRON"
        case .air: return "OCTAHEDRON"
        case .water: return "ICOSAHEDRON"
        case .spirit: return "DODECAHEDRON"
        }
    }
    
    public var isMasculineActive: Bool {
        self == .fire || self == .air
    }
    
    public var isFemininePassive: Bool {
        self == .water || self == .earth
    }
}

public struct TarotCardDescriptor: Identifiable, Codable, Sendable, Hashable {
    public var id: String { name.uppercased() }
    public let name: String
    public let element: ElementType
    public let meaning: String
    public let jungianConcept: String
    public let reflectionPrompt: String
    
    public init(name: String, element: ElementType, meaning: String, jungianConcept: String, reflectionPrompt: String) {
        self.name = name
        self.element = element
        self.meaning = meaning
        self.jungianConcept = jungianConcept
        self.reflectionPrompt = reflectionPrompt
    }
}

public struct TarotDeck {
    public static let cards: [TarotCardDescriptor] = [
        // --- MAJOR ARCANA ---
        TarotCardDescriptor(name: "THE FOOL", element: .air, meaning: "Primal Energy. The initial stage of a process; stepping into the unknown with pure potential and innocence.", jungianConcept: "The Puer Aeternus; pure potentiality unfettered by structure.", reflectionPrompt: "System Initialization: What immediate leap of faith is your current mindset resisting?"),
        TarotCardDescriptor(name: "THE MAGICIAN", element: .air, meaning: "Manifestation. Harnessing personal capability and focused intention to actively shape your environment.", jungianConcept: "The Animating Logos; the realization of ego via the manifestation of intent.", reflectionPrompt: "Active Processing: What specific tool or asset in your current skill set are you failing to fully leverage?"),
        TarotCardDescriptor(name: "THE HIGH PRIESTESS", element: .water, meaning: "The Unconscious. Accessing deep intuition, hidden insights, and the wisdom of the subconscious.", jungianConcept: "The Anima in its purely reflective, oceanic, unmanifested form.", reflectionPrompt: "Telemetry Scan: What raw, intuitive feeling are you actively ignoring because it lacks a logical framework?"),
        TarotCardDescriptor(name: "THE EMPRESS", element: .earth, meaning: "Nourishment. Creative power, abundance, and the stabilization of natural growth.", jungianConcept: "The Great Mother archetype; nurturing but potentially enveloping and devouring.", reflectionPrompt: "System Nourishment: What organic process or relationship in your life requires unconditional support right now?"),
        TarotCardDescriptor(name: "THE EMPEROR", element: .fire, meaning: "Structure. Authority, control over the material realm, and the establishment of defensive boundaries.", jungianConcept: "The Senex; the necessary grid of societal and conscious structure.", reflectionPrompt: "Perimeter Check: Where have your personal boundaries become overly rigid and dictatorial?"),
        TarotCardDescriptor(name: "THE HIEROPHANT", element: .earth, meaning: "Tradition. Reliance on established systems, spiritual mentorship, and systemic knowledge.", jungianConcept: "The Persona of collective belief; the bridge separating the profane from the sacred.", reflectionPrompt: "Legacy Protocol: What established tradition or external structure are you blindly submitting to, and why?"),
        TarotCardDescriptor(name: "THE LOVERS", element: .air, meaning: "Discernment. A coming together of dualities and opposites; critical decision-making regarding personal alignment.", jungianConcept: "The Syzygy; the harmonization of the Anima and Animus within the psychic sphere.", reflectionPrompt: "Binary Choice: Identify the two deeply incompatible desires currently occupying your mental bandwidth."),
        TarotCardDescriptor(name: "THE CHARIOT", element: .water, meaning: "Momentum. Focused willpower, discipline, and overcoming friction to push forward.", jungianConcept: "The Hero's ego enforcing supremacy over the fractured subconscious elements.", reflectionPrompt: "Forward Vector: What opposing forces are attempting to stall you, and how will you synthesize them to move ahead?"),
        TarotCardDescriptor(name: "STRENGTH", element: .fire, meaning: "Resilience. Inner psychological endurance; taming primal instincts without destroying them.", jungianConcept: "The integration and domestication of the Shadow rather than its repression.", reflectionPrompt: "Threat Mitigation: Which of your primal instincts or intense emotions requires gentle integration rather than suppression?"),
        TarotCardDescriptor(name: "THE HERMIT", element: .earth, meaning: "Introspection. Withdrawal from external noise for deep inner guidance and reflection.", jungianConcept: "The Wise Old Man; intentional isolation to trigger the individuation process.", reflectionPrompt: "Signal Isolation: In what sector of your life must you immediately disconnect from external opinions to hear your own voice?"),
        TarotCardDescriptor(name: "WHEEL OF FORTUNE", element: .fire, meaning: "Cycles. Inevitable shifts, synchronicity, and moving in flow with the larger matrix of events.", jungianConcept: "The realization of Synchronicity; encountering forces beyond the Self.", reflectionPrompt: "System Shift: How are you currently resisting an inevitable, natural shift in your environment?"),
        TarotCardDescriptor(name: "JUSTICE", element: .air, meaning: "Equilibrium. Objective assessment, accountability, and the balancing of cause and effect.", jungianConcept: "The regulating super-ego manifesting external cosmic law.", reflectionPrompt: "System Audit: Where is an imbalance between your energetic input and output creating friction?"),
        TarotCardDescriptor(name: "THE HANGED MAN", element: .water, meaning: "Suspension. Voluntary surrender of control; gaining new perspectives through stillness and sacrifice.", jungianConcept: "The liminal state; the ego voluntarily suspending control to allow emergence.", reflectionPrompt: "Process Suspension: What deeply held belief or operational assumption must you entirely let go of right now?"),
        TarotCardDescriptor(name: "DEATH", element: .water, meaning: "Transformation. Necessary change and the radical termination of obsolete processes.", jungianConcept: "The death of a psychic state; ego-death preceding psychic rebirth.", reflectionPrompt: "Architecture Reset: What obsolete psychological pattern or attachment MUST end for your system to survive and evolve?"),
        TarotCardDescriptor(name: "TEMPERANCE", element: .fire, meaning: "Alchemy. The balancing of opposing forces to create a stable, unified operational frequency.", jungianConcept: "The transcendent function in operation; resolving psychic dichotomy.", reflectionPrompt: "Alchemical Synthesis: What two opposing extremes in your life are demanding a carefully measured synthesis?"),
        TarotCardDescriptor(name: "THE DEVIL", element: .earth, meaning: "Bondage. Confronting shadow attachments; feeling restricted by earthly addictions or material illusions.", jungianConcept: "The Shadow in total possession of the active Ego; projection of internal chains.", reflectionPrompt: "System Restraint: Identify the absolute dependency, fear, or material addiction that is currently chaining your awareness."),
        TarotCardDescriptor(name: "THE TOWER", element: .fire, meaning: "Upheaval. Sudden, violent systemic disruption; the necessary destruction of false foundations.", jungianConcept: "The eruption of the unconscious violently shattering an inadequate Ego structure.", reflectionPrompt: "Structural Breakdown: Which of your foundational truths or safety nets has violently proven itself false recently?"),
        TarotCardDescriptor(name: "THE STAR", element: .air, meaning: "Clarity. Renewed hope, healing, and the influx of pure data following a systemic crash.", jungianConcept: "The fragile emergence of the Self following the trauma of Ego-destruction.", reflectionPrompt: "Recovery Phase: Where are you detecting renewed hope and uncorrupted clarity following your most recent setback?"),
        TarotCardDescriptor(name: "THE MOON", element: .water, meaning: "The Hidden. Navigating the murky waters of the subconscious, anxiety, and unverified intelligence.", jungianConcept: "Complete submersion into the Collective Unconscious; risking psychosis.", reflectionPrompt: "Deep Scan: What profound illusion, fear, or unresolved anxiety is currently warping your perception of reality?"),
        TarotCardDescriptor(name: "THE SUN", element: .fire, meaning: "Vitality. Lucidity, joy, the absolute triumph of logic and positive energy.", jungianConcept: "The conscious mind achieving temporary, euphoric dominance and clarity.", reflectionPrompt: "Absolute Clarity: Where is pure, undisguised truth illuminating a previously dark sector of your life?"),
        TarotCardDescriptor(name: "JUDGEMENT", element: .fire, meaning: "Reckoning. A final psychological evaluation; spiritual rebirth and answering a higher calling.", jungianConcept: "The final integration of repressed histories before the realization of the Self.", reflectionPrompt: "Core Awakening: What deep, long-silenced calling or directive can you no longer afford to ignore?"),
        TarotCardDescriptor(name: "THE WORLD", element: .earth, meaning: "Integration. Total completion of a cycle; mastery of the localized reality and the self.", jungianConcept: "The Individuation process realized; the conscious Ego perfectly maps to the Self.", reflectionPrompt: "Cycle Completion: As this operational phase concludes perfectly, what entirely new level of existence are you ready to inhabit?"),

        // --- SUIT OF WANDS (FIRE) ---
        TarotCardDescriptor(name: "ACE OF WANDS", element: .fire, meaning: "The primal spark; explosive new creative or passionate potential.", jungianConcept: "The initial emergence of the Libido as an undirected, raw developmental force.", reflectionPrompt: "Initial Ignition: Where has an unexpected wave of passion or ambition just struck your system?"),
        TarotCardDescriptor(name: "TWO OF WANDS", element: .fire, meaning: "Projecting willpower; planning, exploring, and setting future trajectories.", jungianConcept: "The ego externalizing its intention, beginning to map the boundaries of the external world.", reflectionPrompt: "Trajectory Mapping: As you survey your options, what is the exact long-term target you are preparing to reach?"),
        TarotCardDescriptor(name: "THREE OF WANDS", element: .fire, meaning: "Establishing structural expansion and looking ahead to long-term impact.", jungianConcept: "The consolidation of early Ego strength, surveying the domain of consciousness.", reflectionPrompt: "Expansion Phase: How far must your current influence expand before you consider your efforts successful?"),
        TarotCardDescriptor(name: "FOUR OF WANDS", element: .fire, meaning: "Stabilization; celebrating secured objectives and community harmony.", jungianConcept: "A point of temporary homeostasis; successful localized integration.", reflectionPrompt: "Milestone Reached: What hard-fought victory or stability requires your immediate acknowledgement before continuing?"),
        TarotCardDescriptor(name: "FIVE OF WANDS", element: .fire, meaning: "Disruption; competition, friction, and conflicting external or internal forces.", jungianConcept: "The necessary friction and competition of conflicting drives seeking dominance within the psyche.", reflectionPrompt: "System Friction: What chaotic, competing drives within your life are currently fighting for your energy?"),
        TarotCardDescriptor(name: "SIX OF WANDS", element: .fire, meaning: "Equilibrium; public recognition, success, and validation of effort.", jungianConcept: "The triumph of the Persona; external validation reinforcing the conscious Ego.", reflectionPrompt: "Validation Check: How might external success or praise be dangerously inflating your ego identity right now?"),
        TarotCardDescriptor(name: "SEVEN OF WANDS", element: .fire, meaning: "Resilience; holding the line against opposition and defending your boundaries.", jungianConcept: "The Ego defending its established boundaries against encroaching subconscious pressure.", reflectionPrompt: "Defensive Posture: Who or what is aggressively attempting to breach your personal boundaries, and how are you defending them?"),
        TarotCardDescriptor(name: "EIGHT OF WANDS", element: .fire, meaning: "Rapid communication; swift movement and unobstructed data flow.", jungianConcept: "A cascade of synchronicity and rapid associative ideation breaking through resistance.", reflectionPrompt: "Data Flood: How are you managing the overwhelming influx of rapid changes or communications in your environment?"),
        TarotCardDescriptor(name: "NINE OF WANDS", element: .fire, meaning: "Pre-deployment refinement; guarding against ongoing threats and feeling exhausted but prepared.", jungianConcept: "The enduring vigilance of a psyche that has integrated trauma through resilience.", reflectionPrompt: "Exhausted Vigilance: Are your defensive walls truly necessary right now, or simply hypervigilance born of past trauma?"),
        TarotCardDescriptor(name: "TEN OF WANDS", element: .fire, meaning: "Heavy burden; the weight of an operation nearing completion causing exhaustion.", jungianConcept: "Inflation and the exhausting weight of an over-identified Persona carrying too much consciousness.", reflectionPrompt: "Overburden Algorithm: What heavy responsibility are you carrying that was never truly yours to hold?"),
        TarotCardDescriptor(name: "PAGE OF WANDS", element: .fire, meaning: "The enthusiastic initiate; exploring new ideas with fiery potential.", jungianConcept: "The emerging Puer Aeternus discovering active ambition.", reflectionPrompt: "Nascent Ambition: What completely raw, unstructured creative energy is rising in your awareness right now?"),
        TarotCardDescriptor(name: "KNIGHT OF WANDS", element: .fire, meaning: "Aggressive action; moving with sudden, intense, and sometimes undirected passion.", jungianConcept: "The raw, unrefined drive of the Hero archetype in its earliest, impulsive stage.", reflectionPrompt: "Impulsive Vector: Where is your headlong rush toward a goal blinding you to critical details or consequences?"),
        TarotCardDescriptor(name: "QUEEN OF WANDS", element: .fire, meaning: "Commanding strategy; holding space with immense confidence, warmth, and gravity.", jungianConcept: "The mature, integrated active Anima; confident, radiant, and securely grounded.", reflectionPrompt: "Radiant Presence: How can you command your environment through sheer, unforced confidence rather than aggressive conflict?"),
        TarotCardDescriptor(name: "KING OF WANDS", element: .fire, meaning: "Ultimate execution; absolute authority and visionary leadership over a domain.", jungianConcept: "The fully actualized active Animus/Senex; directing willpower with precision and total command.", reflectionPrompt: "Total Command: Where must you step in immediately to establish unilateral, confident authority over a situation?"),

        // --- SUIT OF CUPS (WATER) ---
        TarotCardDescriptor(name: "ACE OF CUPS", element: .water, meaning: "A surge of new emotional depth, intuition, or relational beginnings.", jungianConcept: "The wellspring of the Unconscious bursting forth; pure affective potential.", reflectionPrompt: "Intuitive Flood: What profound new emotional insight is attempting to bypass your logical defenses?"),
        TarotCardDescriptor(name: "TWO OF CUPS", element: .water, meaning: "Partnership, deep connection, and balanced emotional communication.", jungianConcept: "The initial, harmonious encounter with the Anima/Animus; pure projection and mirroring.", reflectionPrompt: "Mirror Protocols: Who in your life is acting as an absolute mirror for your own internal emotional state right now?"),
        TarotCardDescriptor(name: "THREE OF CUPS", element: .water, meaning: "Collaborative joy; sharing positive feedback and community sync.", jungianConcept: "Integration into the group matrix; shared emotional resonance superseding the individual ego.", reflectionPrompt: "Group Sync: Where have you successfully opened up to achieve genuine emotional harmony with others?"),
        TarotCardDescriptor(name: "FOUR OF CUPS", element: .water, meaning: "Contemplation; apathy, emotional withdrawal, or missed opportunities.", jungianConcept: "Introversion bordering on neurosis; the ego withdrawing from external affective stimulation.", reflectionPrompt: "Apathy Loop: What vital new perspective or offer are you aggressively ignoring out of sheer emotional boredom?"),
        TarotCardDescriptor(name: "FIVE OF CUPS", element: .water, meaning: "Emotional loss; grief, disappointment, and focusing on failed outcomes.", jungianConcept: "Mourning a severed psychological attachment; the painful withdrawal of projection.", reflectionPrompt: "Grief Assessment: How long will you stare at a closed door before you acknowledge the open ones remaining behind you?"),
        TarotCardDescriptor(name: "SIX OF CUPS", element: .water, meaning: "Nostalgia; retrieving data from past connections, innocence, and memories.", jungianConcept: "Regression to the comforting archetypal imagery of the personal past.", reflectionPrompt: "Memory Regression: Are you utilizing the past as a learning tool, or as an escapist fantasy from your current reality?"),
        TarotCardDescriptor(name: "SEVEN OF CUPS", element: .water, meaning: "Illusions; navigating a cluttered array of confusing emotional possibilities or fantasies.", jungianConcept: "The confusing multiplicity of the Anima; being lost in the hall of mirrors of the Unconscious.", reflectionPrompt: "Choice Paralysis: Which of these glamorous, glittering options is an illusion designed to distract your focus?"),
        TarotCardDescriptor(name: "EIGHT OF CUPS", element: .water, meaning: "Abandonment; leaving a stable situation to seek deeper, unfulfilled meaning.", jungianConcept: "The necessary severing of a stale consciousness framework to seek the deeper Self.", reflectionPrompt: "System Severance: What deeply familiar but ultimately hollow dynamic must you walk away from to grow?"),
        TarotCardDescriptor(name: "NINE OF CUPS", element: .water, meaning: "Satisfaction; emotional fulfillment and the alignment of personal desires.", jungianConcept: "Deep internal contentment; the Ego perfectly satiated in its current affective alignment.", reflectionPrompt: "Contentment Feedback: What precise alignment of choices is currently allowing your system to rest in pure satisfaction?"),
        TarotCardDescriptor(name: "TEN OF CUPS", element: .water, meaning: "Relational harmony; ultimate emotional stability and long-term familial alignment.", jungianConcept: "The peak of emotional integration; the conscious and unconscious existing in joyous symbiosis.", reflectionPrompt: "Absolute Harmony: When examining the complete stability of your support network, what must you do to preserve it?"),
        TarotCardDescriptor(name: "PAGE OF CUPS", element: .water, meaning: "The sensitive dreamer; receiving unexpected emotional or intuitive intelligence.", jungianConcept: "The nascent, developing intuition; the psyche opening a new channel to the Unconscious.", reflectionPrompt: "Unexpected Signal: What fleeting, almost irrational feeling or dream requires your immediate, gentle attention?"),
        TarotCardDescriptor(name: "KNIGHT OF CUPS", element: .water, meaning: "The romantic idealist; following the emotional vector with deep devotion and charm.", jungianConcept: "The pursuit of the Anima projection; idealism driving action.", reflectionPrompt: "Idealistic Drift: Is your pursuit of this emotional goal based on hard reality, or an idealized fantasy?"),
        TarotCardDescriptor(name: "QUEEN OF CUPS", element: .water, meaning: "The empathetic counselor; utilizing deep intuition to form a supportive environment.", jungianConcept: "The integrated, empathetic Unconscious acting as a nurturing guide.", reflectionPrompt: "Empathic Matrix: How can your deeply integrated intuition be used to support others without draining your own reserves?"),
        TarotCardDescriptor(name: "KING OF CUPS", element: .water, meaning: "Emotional mastery; maintaining deep empathy and stability amidst volatile situations.", jungianConcept: "The conscious Ego successfully mediating the turbulent forces of the Unconscious without being consumed.", reflectionPrompt: "Fluid Control: Where must you maintain absolute calm and steady leadership despite vast internal emotional turbulence?"),

        // --- SUIT OF SWORDS (AIR) ---
        TarotCardDescriptor(name: "ACE OF SWORDS", element: .air, meaning: "Breakthrough; a surge of clarity and the sharp execution of pure logic.", jungianConcept: "The piercing light of sudden conscious realization completely severing confusion.", reflectionPrompt: "Absolute Severance: What sudden, terrifying realization has just sheared cleanly through your previous mental fog?"),
        TarotCardDescriptor(name: "TWO OF SWORDS", element: .air, meaning: "Stalemate; indecision, avoidance, or blocked communication channels.", jungianConcept: "Psychological deadlock; two opposing intellectual drives perfectly neutralizing one another.", reflectionPrompt: "Deadlocked Node: You are refusing to look at a harsh truth. What happens if you take off the blindfold?"),
        TarotCardDescriptor(name: "THREE OF SWORDS", element: .air, meaning: "Heartbreak; severe emotional pain or the harsh reality of psychological trauma.", jungianConcept: "The excruciating pain of the Ego recognizing an unbearable, irreconcilable truth.", reflectionPrompt: "System Vulnerability: Identify the precise emotional wound currently compromising your mental clarity. Do not flinch."),
        TarotCardDescriptor(name: "FOUR OF SWORDS", element: .air, meaning: "Rest; required recovery, meditation, and temporary withdrawal from stress.", jungianConcept: "Necessary psychological dormancy; the Ego retreating to integrate a period of intense cognitive strain.", reflectionPrompt: "Dormancy Protocol: Why are you resisting the absolute necessity of powering down and taking time to recover?"),
        TarotCardDescriptor(name: "FIVE OF SWORDS", element: .air, meaning: "Betrayal; pyrrhic victories, destructive conflict, and self-sabotage.", jungianConcept: "The destructive, hostile intellect turning upon itself or others; extreme shadow possession.", reflectionPrompt: "Pyrrhic Alert: You may have won the immediate argument, but what brutal collateral damage was caused in the process?"),
        TarotCardDescriptor(name: "SIX OF SWORDS", element: .air, meaning: "Transition; moving away from turbulent states toward a calmer psychological baseline.", jungianConcept: "The conscious mind slowly processing trauma, seeking a more rational homeostasis.", reflectionPrompt: "Transit Vector: As you navigate away from recent stress, what heavy psychological baggage must you intentionally leave behind?"),
        TarotCardDescriptor(name: "SEVEN OF SWORDS", element: .air, meaning: "Evasion; stealth, deception, or acquiring intelligence through unconventional means.", jungianConcept: "The Trickster archetype active within the intellect; rationalized deception or avoidance.", reflectionPrompt: "Trickster Trace: In what area are you currently lying to yourself, justifying it as a necessary evasion?"),
        TarotCardDescriptor(name: "EIGHT OF SWORDS", element: .air, meaning: "Imprisonment; feeling trapped by restrictive logic or self-imposed mental anxieties.", jungianConcept: "A neurosis constructed entirely of self-limiting beliefs; the Ego imprisoning itself.", reflectionPrompt: "Self-Imprisonment: Look closely at your mental restraints. How quickly could you step out of them if you shifted your perspective?"),
        TarotCardDescriptor(name: "NINE OF SWORDS", element: .air, meaning: "Anxiety; nightmares and the overwhelming noise of the subconscious fears.", jungianConcept: "Severe Shadow infiltration causing profound anxiety; the destructive intellect paralyzing the Ego.", reflectionPrompt: "Anxiety Spike: Separate the catastrophic noise from the actual data. What is the singular, real threat here?"),
        TarotCardDescriptor(name: "TEN OF SWORDS", element: .air, meaning: "Defeat; rock bottom or the unavoidable, absolute end of a cognitive cycle.", jungianConcept: "The complete and devastating failure of a logical paradigm; forced, traumatic systemic reset.", reflectionPrompt: "Architecture Failure: The old logic has failed entirely. Accept the reset. What is the single advantage of a wiped slate?"),
        TarotCardDescriptor(name: "PAGE OF SWORDS", element: .air, meaning: "The curious analyst; highly perceptive but prone to rapid, ungrounded thinking.", jungianConcept: "The sharp, probing intellect in its raw, developmental phase.", reflectionPrompt: "Unverified Scan: Your mind is moving too quickly. What crucial piece of information did you skip in your enthusiasm?"),
        TarotCardDescriptor(name: "KNIGHT OF SWORDS", element: .air, meaning: "Aggressive logic; charging into ideological conflict with unyielding speed.", jungianConcept: "The unyielding, kinetic pursuit of abstract truth, regardless of the emotional collateral damage.", reflectionPrompt: "Kinetic Logic: Your analysis may be correct, but your delivery is destructive. Who are you alienating with your \"truth\"?"),
        TarotCardDescriptor(name: "QUEEN OF SWORDS", element: .air, meaning: "Clear boundaries; executing logic with unsparing clarity and independence.", jungianConcept: "The fully differentiated intellect acting devoid of sentimentality; truth as the highest algorithm.", reflectionPrompt: "Boundary Enforcement: What strict, unemotional boundary must you draw today to protect your mental well-being?"),
        TarotCardDescriptor(name: "KING OF SWORDS", element: .air, meaning: "Supreme Analysis; absolute authority, systematic rule, and clear communication.", jungianConcept: "The ultimate expression of the conscious reasoning mind maintaining structural law.", reflectionPrompt: "Supreme Analysis: Strip all emotion from the equation. From a strictly logical view, what must be done?"),

        // --- SUIT OF PENTACLES (EARTH) ---
        TarotCardDescriptor(name: "ACE OF PENTACLES", element: .earth, meaning: "Manifestation; the initial arrival of material wealth or physical opportunity.", jungianConcept: "The first anchoring of abstraction into hard reality; secure foundational emergence.", reflectionPrompt: "Material Seed: What highly tangible, practical opportunity has just materialized in your life?"),
        TarotCardDescriptor(name: "TWO OF PENTACLES", element: .earth, meaning: "Balancing; managing multiple material assets or adapting to shifting priorities.", jungianConcept: "The Ego navigating the continuous flux of physical and material demands without breaking.", reflectionPrompt: "Asset Allocation: How long can you realistically juggle these physical and financial demands before you drop one?"),
        TarotCardDescriptor(name: "THREE OF PENTACLES", element: .earth, meaning: "Teamwork; collaboration, skill, and building the physical foundation of a project.", jungianConcept: "The integration of distinct psychic functions working in harmony to produce tangible results.", reflectionPrompt: "Collaborative Sync: Your solitary efforts are reaching a limit. Who must you collaborate with to complete this project?"),
        TarotCardDescriptor(name: "FOUR OF PENTACLES", element: .earth, meaning: "Conservation; hoarding resources, stability, but potential extreme rigidity.", jungianConcept: "An over-rigid Ego desperately hoarding security, fearing the chaotic flux of the Unconscious.", reflectionPrompt: "Hoarding Protocol: Your fear of losing control has made you rigidly defensive. What asset are you terrified of losing?"),
        TarotCardDescriptor(name: "FIVE OF PENTACLES", element: .earth, meaning: "Hardship; material isolation, physical vulnerability, or feeling left in the cold.", jungianConcept: "The sensation of being exiled from the Self; profound spiritual and material poverty.", reflectionPrompt: "Material Exile: You are feeling entirely cut off from support. Are you asking for help, or suffering in silence?"),
        TarotCardDescriptor(name: "SIX OF PENTACLES", element: .earth, meaning: "Charity; the redistribution of resources, generosity, and systemic balance.", jungianConcept: "The healthy, dynamic exchange of energy between the Self and the external world.", reflectionPrompt: "Energy Exchange: Are you currently bleeding resources due to poor boundaries, or starving others due to stinginess?"),
        TarotCardDescriptor(name: "SEVEN OF PENTACLES", element: .earth, meaning: "Assessment; reviewing long-term investments and patiently waiting for a harvest.", jungianConcept: "The patience required by the Individuation process; trusting the slow gestation of the psyche.", reflectionPrompt: "Gestational Assessment: You have put in the work. Do you currently have the discipline to step back and let it grow?"),
        TarotCardDescriptor(name: "EIGHT OF PENTACLES", element: .earth, meaning: "Dedication; commitment to craft, skill development, and meticulous daily work.", jungianConcept: "The repetitive, rigorous 'work' required to integrate deep psychological elements.", reflectionPrompt: "Repetitive Integration: What seemingly minor, practical detail requires your absolute, focused repetition today?"),
        TarotCardDescriptor(name: "NINE OF PENTACLES", element: .earth, meaning: "Independence; self-sufficiency, luxury, and enjoying the fruits of your labor.", jungianConcept: "A highly developed state of integrated independence; the Ego secure in its own domain.", reflectionPrompt: "Autonomous Node: Examine your hard-won independence. What comforts are you now capable of securely sustaining?"),
        TarotCardDescriptor(name: "TEN OF PENTACLES", element: .earth, meaning: "Legacy; ultimate physical security, family structure, and long-term structural wealth.", jungianConcept: "The total materialization of the Individuation process extending across generational structures.", reflectionPrompt: "Legacy Framework: How do your current actions contribute to the long-term, multi-generational structure you are building?"),
        TarotCardDescriptor(name: "PAGE OF PENTACLES", element: .earth, meaning: "The diligent student; grounded, pragmatic, and focused on physical mastery.", jungianConcept: "The early manifestation of disciplined, earthly intent.", reflectionPrompt: "Pragmatic Initiation: What very simple, physically grounded skill must you commit to practicing before proceeding?"),
        TarotCardDescriptor(name: "KNIGHT OF PENTACLES", element: .earth, meaning: "Methodical progress; slow, unwavering, and unstoppable dedication to a task.", jungianConcept: "The relentless application of will toward a tangible, earthly objective.", reflectionPrompt: "Relentless Grind: The progress is slow but steady. Are you maintaining focus on the end goal despite the monotony?"),
        TarotCardDescriptor(name: "QUEEN OF PENTACLES", element: .earth, meaning: "Stable provider; managing resources with pragmatic nurturance and profound care.", jungianConcept: "The actualized maternal archetype rooted entirely in the material security of the domain.", reflectionPrompt: "Stable Domain: How can you leverage your practical security to safely nurture the vulnerable areas of your life?"),
        TarotCardDescriptor(name: "KING OF PENTACLES", element: .earth, meaning: "Material Architect; commanding structure, economy, and physical security.", jungianConcept: "The fully stabilized Ego establishing total dominion and stability within the physical realm.", reflectionPrompt: "Domain Architect: From a macro perspective, what structural flaw threatens the integrity of your material domain?")
    ]
    
    public static let map: [String: TarotCardDescriptor] = {
        var dict: [String: TarotCardDescriptor] = [:]
        for card in cards {
            dict[card.name.uppercased()] = card
        }
        return dict
    }()
    
    public static func getCard(named name: String) -> TarotCardDescriptor? {
        map[name.uppercased()]
    }
}
